import { motion } from 'framer-motion';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui';
import { FileText, Clock, Sparkles } from 'lucide-react';

interface Document {
  id: string;
  title: string;
  type: 'policy' | 'claim' | 'report';
  lastUpdated: string;
  status?: string;
}

const mockDocuments: Document[] = [
  { id: '1', title: 'Smith Auto Policy', type: 'policy', lastUpdated: '2 days ago' },
  { id: '2', title: 'ABC Claim Report', type: 'claim', lastUpdated: 'Pending review', status: 'pending' },
  { id: '3', title: 'Q1 Portfolio Review', type: 'report', lastUpdated: 'Generated by AI' },
];

const typeIcons = {
  policy: '📝',
  claim: '📋',
  report: '📊',
};

export function DocumentManagement() {
  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="text-base flex items-center gap-2">
          <FileText className="h-4 w-4" />
          Integrated Document Management
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          {mockDocuments.map((doc, index) => (
            <motion.div
              key={doc.id}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.3, delay: index * 0.1 }}
              whileHover={{ scale: 1.02 }}
              className="p-3 bg-muted/50 rounded-lg cursor-pointer hover:bg-muted transition-colors"
            >
              <div className="flex items-start gap-2">
                <span className="text-lg">{typeIcons[doc.type]}</span>
                <div>
                  <div className="font-medium text-sm">{doc.title}</div>
                  <div className="text-xs text-muted-foreground flex items-center gap-1 mt-1">
                    {doc.type === 'report' ? (
                      <Sparkles className="h-3 w-3" />
                    ) : (
                      <Clock className="h-3 w-3" />
                    )}
                    {doc.lastUpdated}
                  </div>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </CardContent>
    </Card>
  );
}
